Repository itworkedonmymachine/panoptes, pull requests merged in 2021-01, with the labels that each got.

#16 Feat/statuspage
  .eslintrc.js
  src/App.svelte
  src/component/StatusTicker.svelte
  src/helper/statuspageHelper.js
  src/mockStatusData.js
  src/store/statuspageStore.js
  test/component/StatusTicker.test.js
Labels: enhancement

#18 feat(add searchbar): add searchbar and jest
  src/component/SearchBar.svelte
  test/component/SearchBar.test.js
Labels: enhancement

#20 Adjust header height with width < 760px
  src/App.svelte
Labels: refactor

#24 Deploy to gh-pages after release
  .github/workflows/release-and-deploy.yml
  package.json
Labels: enhancement

#27 Implement modal component
  src/component/Modal.svelte
  test/component/Modal.test.js
  test/component/ModalSlotTest.svelte
Labels: enhancement

#28 Implement watchlist
  src/App.svelte
  src/component/Watchlist.svelte
  src/component/WatchlistItem.svelte
  src/container/Header.svelte
  src/main.js
  test/component/Watchlist.test.js
  test/component/WatchlistItem.test.js
  test/container/Header.test.js
Labels: enhancement

#30 Set favicon & title
  public/favicon.png
  public/index.html
Labels: style

#33 Use roboto for this project
  public/global.css
  public/index.html
Labels: refactor, style

#35 Fetch status from status.io
  src/helper/statusioHelper.js
  src/store/statusioStore.js
Labels: enhancement

#36 Implement search bar
  src/component/SearchBar.svelte
  test/component/SearchBar.test.js
Labels: enhancement, style

#40 Add templates for ISSUE, PULL REQUEST
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#39 Manage store with store pool
  .eslintrc.js
  src/component/SearchBar.svelte
  src/component/StatusTicker.svelte
  src/component/Watchlist.svelte
  src/helper/statusioHelper.js
  src/helper/statuspageHelper.js
  src/interface/statusioStoreInterface.js
  src/interface/statuspageStoreInterface.js
  src/interface/storeInterface.js
  src/static/statusioPairs.js
  src/static/statuspagePairs.js
  src/store/statusStorePool.js
  src/store/statusioStore.js
  src/store/statuspageStore.js
Labels: refactor

#43 Add Close button to modal
  src/component/Modal.svelte
  test/component/Modal.test.js
Labels: enhancement

#45 Apply style for search bar
  src/component/SearchBar.svelte
  test/component/SearchBar.test.js
Labels: refactor, style

#46 Show search bar when user clicks search
  src/component/Modal.svelte
  src/component/SearchBar.svelte
  src/container/Header.svelte
  test/container/Header.test.js
Labels: enhancement

#48 refactor(search-bar): use clear as input clear
  src/component/SearchBar.svelte
  test/component/SearchBar.test.js
Labels: refactor

#50 Use mock data for component test
  test/component/Watchlist.test.js
Labels: refactor

#52 Focus search bar after clear
  src/component/SearchBar.svelte
  test/component/SearchBar.test.js
Labels: enhancement

#55 Disable scroll on body if modal is open, enable scroll on search bar
  public/global.css
  src/component/Modal.svelte
  src/component/SearchBar.svelte
  test/component/SearchBar.test.js
Labels: bug

#57 Manage user selections with store
  src/component/SearchBar.svelte
  src/store/watchListStore.js
  test/component/SearchBar.test.js
  test/store/watchListStore.test.js
Labels: enhancement

#60 Render watchlist with user selected platform
  src/component/SearchBar.svelte
  src/component/Watchlist.svelte
  src/store/watchListStore.js
  src/store/watchlistStore.js
  test/component/SearchBar.test.js
  test/component/Watchlist.test.js
  test/store/watchListStore.test.js
  test/store/watchlistStore.test.js
Labels: enhancement, refactor

#63 Support dark mode
  public/global.css
  src/App.svelte
  src/component/Modal.svelte
  src/component/SearchBar.svelte
  src/component/StatusTicker.svelte
  src/container/Header.svelte
  test/component/Modal.test.js
  test/component/SearchBar.test.js
  test/component/StatusTicker.test.js
  test/container/Header.test.js
Labels: enhancement, refactor

#65 Set status color as global variable
  src/App.svelte
  src/component/StatusTickerItem.svelte
  src/component/WatchlistItem.svelte
  test/component/StatusTickerItem.test.js
  test/component/WatchlistItem.test.js
Labels: bug, refactor

#67 Set background color of header
  src/container/Header.svelte
  test/container/Header.test.js
Labels: bug

#69 Add maintenance status in summarized data
  src/App.svelte
  src/component/StatusTickerItem.svelte
  src/component/WatchlistItem.svelte
  src/store/statusioStore.js
  src/store/statuspageStore.js
  test/component/StatusTickerItem.test.js
  test/component/WatchlistItem.test.js
Labels: enhancement

#70 Add simple quote to indicate adding platforms
  src/component/Watchlist.svelte
  test/component/Watchlist.test.js
Labels: enhancement

#71 Let mobile user open action bar with touch scroll
  src/App.svelte
  src/component/ActionBar.svelte
  src/container/Header.svelte
  src/container/SearchModal.svelte
  src/store/modalStore.js
  test/component/ActionBar.test.js
  test/container/Header.test.js
  test/container/SearchModal.test.js
Labels: enhancement

#75 Open settings modal if settings is clicked
  src/App.svelte
  src/component/ActionBar.svelte
  src/component/Settings.svelte
  src/container/Header.svelte
  src/container/SettingsModal.svelte
  src/store/modalStore.js
  src/svg-icon/Moon.svelte
  src/svg-icon/Sun.svelte
  test/component/ActionBar.test.js
  test/component/Settings.test.js
  test/container/Header.test.js
Labels: enhancement

#77 Add href link of status page to watchlist item
  public/global.css
  src/component/Watchlist.svelte
  src/component/WatchlistItem.svelte
  src/interface/statusioStoreInterface.js
  src/interface/statuspageStoreInterface.js
  src/interface/storeInterface.js
  test/component/Watchlist.test.js
Labels: enhancement

#76 Implement mode toggle in Settings
  src/component/Settings.svelte
  src/style/globalColorVariables.js
  test/component/Settings.test.js
Labels: enhancement
